spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        transaction.coordinator_class: jta
        jta.platform: org.hibernate.service.jta.platform.internal.JBossAppServerJtaPlatform
    open-in-view: false
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method